version: '3'
services:
    client:
      stdin_open: true
      restart: always
      build:
        dockerfile: Dockerfile.dev
        context: ./client
      volumes:
        - /app/node_modules
        - ./client:/app
    api:
      restart: always
      build:
        dockerfile: Dockerfile.dev
        context: ./server
      volumes:
        - /app/node_modules
        - ./server:/app
    nginx:
      restart: always
      build:
          dockerfile: Dockerfile.dev
          context: ./nginx
      ports:
        - '3050:80'      
